### ISSUE TITLE
Random database creation errors with make check

### ISSUE THREAD

**Issue by pnorman** [zerebubuth/openstreetmap-cgimap#81]
`make check -j8` sometimes gives me this error

```
====================================
   CGImap 0.3.0: ./test-suite.log
====================================

8 of 9 tests failed.

.. contents:: :depth: 2


FAIL: test/test_empty.rb (exit: 1)
==================================


=== Testing read-write ===
=== Testing read-only ===
createdb: database creation failed: ERROR:  source database "template1" is being accessed by other users
DETAIL:  There are 1 other session(s) using the database.
pidfile /tmp/tmp.xdyGpEbk7a/cgimap.pid doesn't exist!

FAIL: test/test_map.rb (exit: 1)
================================

=== Testing read-write ===
/home/pnorman/osm/openstreetmap-cgimap/test/test_functions.rb:15:in `assert': Expected false, got true: "FCGI should have returned headers." (AssertionError)
        from /home/pnorman/osm/openstreetmap-cgimap/test/test_functions.rb:28:in `block in test_request'
        from /usr/lib/ruby/1.9.1/open3.rb:208:in `popen_run'
        from /usr/lib/ruby/1.9.1/open3.rb:90:in `popen3'
        from /home/pnorman/osm/openstreetmap-cgimap/test/test_functions.rb:25:in `test_request'
        from ./test/test_map.rb:26:in `block in <main>'
        from ./test/test_map.rb:17:in `each'
        from ./test/test_map.rb:17:in `<main>'
test/test-single.sh: line 19: kill: (18691) - No such process
```

I also have a bunch of databases like `openstreetmap_15031_11039` but that could be from a previous run.

**Comment by zerebubuth** [comment]
Sorry, this is really old...

Since the tests were all moved to C++, have you seen this problem? I think we've only got the one APIDB test now, which presumably means concurrency is less of a problem.

**Comment by pnorman** [comment]
I haven't run it lately, but what you describe should fix it.
